spring:
  application:
    name: bank-customer
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mentoria
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true


server:
  port: 9092
